### ISSUE TITLE
Reference to your .css file in another project

### ISSUE THREAD

**Issue by Klemet** [m-clark/generalized-additive-models#13]
Hello, Mr. Clark !

I just wanted to ask you if you'd be OK with me adapting your .css code for Bookdown for some of my projects.[ I referenced your work and your personal page in the .css file](https://github.com/Klemet/Workshop-Organization-FR/blob/5789ae268caeaafecadb56a55eaa9e2f933cdf22/book.css#L1), but I can do it elsewhere too if you deem it appropriate.

In addition, I also added a couple of lines to "fix" some of what I considered small issues. I'll list them here if you're interested to incorporate them into your version.

- [Fixed the width of horizontal lines](https://github.com/Klemet/Workshop-Organization-FR/blob/5789ae268caeaafecadb56a55eaa9e2f933cdf22/book.css#L82)
- [Remove the font setting button](https://github.com/Klemet/Workshop-Organization-FR/blob/5789ae268caeaafecadb56a55eaa9e2f933cdf22/book.css#L88)
- [Fix the width of sub elements in lists](https://github.com/Klemet/Workshop-Organization-FR/blob/5789ae268caeaafecadb56a55eaa9e2f933cdf22/book.css#L323)

In any case, I just wanted to say that your .css is really amazing to make Bookdown shine !

**Comment by m-clark** [comment]
Very sorry for the belated reply, but yes, feel free to use, and glad they can be of help.  At some point I'll update that doc, so will try to incorporate those fixes as well. Thanks for pointing them out!
