### ISSUE TITLE
document display  errors

### ISSUE THREAD

**Issue by leiallen521** [m-clark/generalized-additive-models#16]
Hi Micheal, 
              i open the document seems like not at a ideal state today,  i post it below.   It works well two weeks ago , i remember...
![image](https://user-images.githubusercontent.com/81500134/203523380-7a1ac489-6ace-4024-800a-82e077c734fe.png)

**Comment by m-clark** [comment]
Sorry I missed this, but it looks like it was a random internet hiccup.
